# fly.toml app configuration file generated for insanely-fast-whisper-api-jp-tesis on 2024-10-16T15:06:11-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'insanely-fast-whisper-api-jp-tesis'
primary_region = 'sjc'

[build]

[[mounts]]
  source = 'data'
  destination = '/root/.cache'
  initial_size = '30gb'

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'a100-80gb'
  memory = '8gb'
  cpu_kind = 'performance'
  cpus = 4
